FROM ubuntu:noble-20250910
LABEL org.opencontainers.image.authors="carlos@florez.co.uk"
LABEL org.opencontainers.image.version="2.6.3"

ARG LOCALTIME=UTC
ARG DEBIAN_FRONTEND=noninteractive

# Maven needs to be bumped up on any new release, see install-dependencies.sh for url
ARG MAVEN_CURRENT_VERSION=3.9.15
ARG JDTLS_CURRENT_VERSION=1.50.0
ARG JDTLS_CURRENT_BUILD=202509041425
ARG PYTHON_VERSIONS="3.11.6 3.12.10"
ARG PYTHON_DEFAULT=3.12

ENV TMP_SCRIPTS=/tmp/scripts
ENV TMP_CONFIG=/tmp/config
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US
ENV LC_ALL=en_US.UTF-8
ENV TERM=xterm-256color
ENV LOCALTIME=$LOCALTIME
ENV MAVEN_CURRENT_VERSION=$MAVEN_CURRENT_VERSION
ENV JDTLS_CURRENT_VERSION=$JDTLS_CURRENT_VERSION
ENV JDTLS_CURRENT_BUILD=$JDTLS_CURRENT_BUILD
ENV PYTHON_VERSIONS=$PYTHON_VERSIONS
ENV PYTHON_DEFAULT=$PYTHON_DEFAULT
ENV DOT_HOME=/usr/local/src/dotfiles
ENV DOT_HOME_SCRIPTS=$DOT_HOME/scripts
ENV DOT_HOME_LIB=$DOT_HOME/lib
ENV DOT_HOME_VIM=$DOT_HOME/vim
ENV MAVEN_HOME=$DOT_HOME_LIB/maven/apache-maven-$MAVEN_CURRENT_VERSION

SHELL ["/bin/bash", "-c"]
RUN mkdir {$DOT_HOME,$DOT_HOME_SCRIPTS,$DOT_HOME_LIB,$DOT_HOME_VIM,$DOT_HOME_LIB/jdtls,$DOT_HOME_LIB/maven}

ADD ./lib $DOT_HOME_LIB

RUN mkdir -p $TMP_SCRIPTS $TMP_CONFIG
ADD ./scripts $TMP_SCRIPTS
ADD ./config $TMP_CONFIG
RUN chmod +x -R $TMP_SCRIPTS  
RUN ln -s /usr/share/zoneinfo/$LOCALTIME /etc/localtime
# 24.04 introduced a new ubuntu (1000) user
RUN groupmod -g 1099 ubuntu
RUN usermod -u 1099 ubuntu

# Installation/config script
RUN $TMP_SCRIPTS/install-dependencies.sh

RUN rm -r $TMP_SCRIPTS $TMP_CONFIG
