name: ci

on:
  release:
    types: [created]
		
env:
  OWNER: ${{ github.actor }}
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build --no-cache -t ghcr.io/$OWNER/dev-env-ubuntu-base-img:$TAG .
          docker push ghcr.io/$OWNER/dev-env-ubuntu-base-img:$TAG

        
