name: docker-image

on:
  release:
    types: [created]

env:
  OWNER: ${{ gihub.actor }}
  TAG: ${{ github.ref_name }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: $OWNER
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
	    docker build --no-cache -t ghcr.io/$OWNER/dev-env-ubuntu-base-img:$TAG .
        docker push ghcr.io/$OWNER/dev-env-ubuntu-base-img:$TAG

